### ISSUE TITLE
https request using port 80 when not specified

### ISSUE THREAD

**Issue by sheakelly** [sindresorhus/got#131]
I am having some issues doing npm install of the pngquant-bin package via a squid proxy. The root cause from what I can see is that the kevva/download module sets up a http-agent and passes some options in to `function requestAsEventEmitter(opts)`. The result it that the following line selecting https
````
var fn = opts.protocol === 'https:' ? https : http;
````
However the request on the squid log is as follows which shows the outgoing request on port 80
````
TCP_TUNNEL/200 0 CONNECT raw.github.com:80
````
When I change the code to 
````
var fn = opts.protocol === 'https:' ? https : http;
opts.port = 443;
````
The squid log show the correct port https is used and the download is successful
````
TCP_TUNNEL/200 0 CONNECT raw.github.com:443
```` 
The https lib documentation https://nodejs.org/api/https.html#https_https_request_options_callback states that port 443 is the default but it does not appear to work that way atleast when a proxy is involved

Not entirely sure if this is a bug in this module or the kevva/download module or indeed the https node library

I am experience the same issue node 0.12.x and 4.2.x

**Comment by floatdrop** [comment]
@sheakelly seems like `https://` is missing in url argument. Could you provide example how to reproduce?

**Comment by sheakelly** [comment]
````
var https = require('https');

var request = function(opts) {
  console.log('hostname: ' + opts.hostname);
  console.log('path: ' + opts.path);
  var req = https.request(opts, function(res) {
    console.log('res.statusCode: ' + res.statusCode);
    console.log('res.headers.location: ' + res.headers.location);
  });

  req.end();

  req.on('error', function(e) {
    console.error(e);
  });
};

var opts = {
  hostname: 'raw.github.com',
  path: '/imagemin/pngquant-bin/v3.0.0/vendor/win/pngquant.exe',
  method: 'GET'
};

request(opts);
````
When you run the example code above the console output is as follows:

````
hostname: raw.github.com
path: /imagemin/pngquant-bin/v3.0.0/vendor/win/pngquant.exe
res.statusCode: 301
res.headers.location: https://raw.githubusercontent.com/imagemin/pngquant-bin/v3.0.0/vendor/win/pngquant.exe
````
This is showing that despite using the 'https' library a non-secure request is sent and github is redirecting to ssl. So I think you need to set the port to 443 explicitly

**Comment by floatdrop** [comment]
> This is showing that despite using the 'https' library a non-secure request is sent and github is redirecting to ssl. So I think you need to set the port to 443 explicitly

@sheakelly why so? github redirecting you to https endpoint.

**Comment by sheakelly** [comment]
That is exactly the problem. The code is attempting to make a https request by using the 'https' library. But the request is sent outbound as a non-secure http request because the port is not set as 443. The result is a 301 redirect to the secure version of the url. 

In your module you are using the following code to select whether or not to make a secure or non-secure http request. Looks like you will *always* be making a non-secure request.
````
var fn = opts.protocol === 'https:' ? https : http;
````
That might be ok in some cases however the issue I am experiencing is that when the request is via a squid proxy using a http agent. The 'got' module issues a http request over a https secure tunnel. This confuses the squid proxy. 

There are a few npm packages involved in this issue so I am a bit unsure which package should be patched. The dependency chain is:  imagemin/pngquant-bin -> kevva/download -> sindresorhus/got. The http agent is setup via the kevva/caw package the uses mikeal/tunnel-agent to create the tunnelling socket when the proxy is configured.

**Comment by floatdrop** [comment]
@sheakelly that's strange, [`https.request` docs](https://nodejs.org/api/https.html#https_https_request_options_callback) says:

> port: Port of remote server. Defaults to 443.

So it should work fine (unless you specify port explicitly).

**Comment by shinnn** [comment]
https://github.com/kevva/download/issues/85 is fixed.

@sheakelly Can you try [download](https://github.com/kevva/download) v4.4.2?

**Comment by sheakelly** [comment]
I have tested with the latest version or(download)[https://github.com/kevva/download] (v4.4.3) and gettting the same issue. Still getting a request on port 80.
````
TCP_TUNNEL/200 0 CONNECT raw.github.com:80
````
I understand that the docs say the port defaults to 443 however if you run the code in my second comment you will get a redirect response from github. i.e. even though you are using the 'https' library you are making a non-secure request. Do you think this is a bug with nodejs? Should log it there?

**Comment by floatdrop** [comment]
@sheakelly modify your code to use location, that github retruned in redirect and you will get `200` response. If you replace `require('https')` to `require('http')` you will get `301` again (even with fixed location). I'm quite sure, that there is no error in `http` or `https` library and port is set correctly. Probably proxy setup is broken.

**Comment by sheakelly** [comment]
Unfortunately the url is not under my control. But my code above is reproducing the issue. The problem is also not specific to a proxy configuration. Without a proxy agent configured 'https' lib will request over port 80 and github redirects to port 443.The redirect if followed perfectly by your library hiding the problem however when I use a squid proxy the request just hangs. I acknowledge that the documentation says it should default to 443. Just does not appear to behave that way. I will raise an issue with the nodejs team. Thanks for your help and responding quickly to my issue. I will let you know if I find out any more details.

**Comment by shinnn** [comment]
Will be fixed in [the upstream project](https://github.com/mikeal/tunnel-agent). https://github.com/mikeal/tunnel-agent/pull/15

**Comment by marc-guenther** [comment]
which has just been released as 0.4.2 :)
