### ISSUE TITLE
AfterResponse hook invalid behaviour (JSON parsing)

### ISSUE THREAD

**Issue by przemos** [sindresorhus/got#808]
#### Describe the bug

 - Node.js version: all
 - OS & version: all
#### What would you like to discuss?

I've noticed an odd behaviour when calling get method on the got client with json:true option and with afterResponse hook installed (with got.extend).  The response in **as-promise.js** is parsed twice and thus causing an error.

First, afterResponse hook is generating a Promise which tries to parse response.body of the new response with fragment  `if (options.json && response.body) {`
When the promise is resolved and returned as a result of hook execution:
`response = await hook(response, updatedOptions => {`
it is processed again by the same piece of code:
`if (options.json && response.body) {`
which causes an error as response body has been already parsed in the afterResponse related hook promise and this time
`JSON.parse(response.body); `
fails.

#### Actual behavior

Currently parent promise generates a child promise (afterResponse hook promise) which processes the response just as the parent promise would if there were no afterResponse hook. This causes double processing and JSON.parse being called twice which result in an error.

#### Expected behavior
Once the  child promise is resolved (afterResponse hook) with response, it should not be processed by parent promise as it has been already by child promise. The parent promise should be resolved immediately with the response of the child promise.
...

#### Code to reproduce
1) Client init:
```
const client = got.extend({
            hooks: {
                afterResponse: [
                    async (response: any, withUpdatedOptions: any) => {
                        if (response.statusCode === 401) {
                                const newAuthorizationOptions = { };
                                return withUpdatedOptions(newAuthorizationOptions);
                        }
                        return response;
                    }
                ]
            }
        });
```
2) Client call
```
 await client.get(path,
                {
                    json: true, 
                });

```

#### Checklist

- [ x] I have read the documentation.
- [ x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
1. Fill out the template properly.

> Node.js version: all

What do you mean by "all"? Please specify.

> OS & version: all

So you tried Windows, MacOS, FreeBSD, Mint, Solus, Ubuntu (+ bunch of other distros?)

Please specify.

2. This is already fixed on master branch.

**Comment by przemos** [comment]
cool, thanks, though, this is code issue so it is independent of node version or OS. 
Master branch points to code in flux, so officially it is not fixed yet :)

**Comment by szmarczak** [comment]
> this is code issue so it is independent of node version or OS.

Not right. Some node modules work different for different OSes. When we ask for it, please fill out. Otherwise your issue could get marked as "invalid".

> Master branch points to code in flux, so officially it is not fixed yet :)

It is, but we haven't released it yet. Please look for merged PRs and see if the bug had been fixed before making a bug issue.
